"""
Enhanced narrative templates with extensive conditional text based on world state,
character emotional states, and relationship contexts.
"""

def get_enhanced_templates():
    """
    Returns a dictionary of template categories with multiple rich template variations.
    Templates use conditional rendering, randomization, and pronoun handling.
    """
    return {
        # Location-based events
        "location_entry": [
            "{actor.name} enters {location}, {IF is_familiar}moving with the confidence of familiarity{ELSE}taking in the unfamiliar surroundings with {IF actor.emotions.curiosity > 5}keen interest{ELSE}cautious observation{ENDIF}{ENDIF}. {IF world_state.economic_status == 'DEPRESSION'}The place bears visible signs of hard times, {RANDOM[with fewer patrons than the space could hold|items of value conspicuously absent|a lingering atmosphere of worry]}.{ELIF world_state.economic_status == 'BOOM'}The place bustles with activity and prosperity, {RANDOM[patrons spending freely|valuable goods prominently displayed|an atmosphere of optimism prevailing]}.{ELSE}The atmosphere is neither particularly prosperous nor desperate.{ENDIF}",
            
            "As {actor.name} arrives at {location}, {actor.subjective} {IF actor.emotions.fear > 5}nervously scans for potential threats{ELIF actor.emotions.joy > 5}breaks into a smile at the familiar sights{ELSE}maintains a neutral expression while assessing the surroundings{ENDIF}. {IF world_state.political_stability == 'UNREST'}Tension hangs in the air, with {RANDOM[people speaking in hushed tones|guards watching everyone with suspicion|propaganda posters newly plastered on walls]}.{ELIF world_state.political_stability == 'PEACEFUL'}A sense of security pervades the space, with {RANDOM[people engaging openly in conversation|minimal security presence|public gatherings occurring freely]}.{ENDIF}",
            
            "{actor.name} steps into {location}. {IF time_of_day == 'night'}The darkness is {RANDOM[periodically broken by torch light|deepened by the absence of the usual crowds|made mysterious by strange shadows]}.{ELSE}Sunlight reveals {RANDOM[dust motes dancing in the air|the full activity of the space|details that might be missed in dimmer light]}.{ENDIF} {IF world_state.active_global_threats}Signs of the {threat_name} are evident in {RANDOM[the nervous glances people exchange|the unusual preparations visible|the topics of hushed conversation]}.{ENDIF}"
        ],
        
        "location_discovery": [
            "{actor.name} discovers {location} for the first time. {IF actor.emotions.curiosity > 5}With eager eyes, {actor.subjective} {RANDOM[examines every detail|drinks in the new sights|mentally catalogs the unfamiliar elements]}.{ELSE}{Actor.subjective} surveys the area with {RANDOM[measured interest|practical assessment|cautious attention]}.{ENDIF} {IF world_state.current_season == 'winter'}The winter's touch is evident in {RANDOM[frost-covered surfaces|the biting chill in the air|people huddled near sources of warmth]}.{ELIF world_state.current_season == 'summer'}Summer heat defines the space, with {RANDOM[people seeking shade|a languid atmosphere|shimmering air above sun-baked surfaces]}.{ENDIF}",
            
            "A new vista opens before {actor.name}: {location} stretches before {actor.objective}, {IF is_expected}matching the descriptions {actor.subjective}'d heard{ELSE}contrary to what {actor.subjective} had anticipated{ENDIF}. {IF world_state.political_stability == 'WAR'}Signs of conflict are {RANDOM[unmistakable in the fortifications|evident in the wary population|clear from the military presence]}.{ELIF location_type == 'ruins'}Ancient grandeur now lies in decay, {RANDOM[columns toppled by time|nature reclaiming stone structures|artifacts half-buried in debris]}.{ELIF location_type == 'settlement'}The settlement shows signs of being {RANDOM[carefully planned|organically grown over time|adapted to the natural features of the land]}.{ENDIF}",
            
            "{actor.name}'s exploration leads to {location}. {IF actor.domain.AWARENESS > 3}With keen senses, {actor.subjective} immediately notes {RANDOM[the unusual layout|subtle signs of recent activity|potential points of interest or concern]}.{ELSE}It takes some time for {actor.objective} to orient and understand the space.{ENDIF} {IF world_state.economic_status == 'BOOM'}Signs of prosperity are evident in {RANDOM[new construction|well-maintained features|valuable materials used]}.{ELIF world_state.economic_status == 'DEPRESSION'}The effects of hard times show in {RANDOM[neglected maintenance|makeshift repairs|abandoned sections]}.{ENDIF}"
        ],
        
        # Domain check outcomes
        "domain_check_success": [
            "Drawing on {domain} expertise, {actor.name} {action} with {RANDOM[practiced ease|remarkable skill|confident precision]}. {IF margin > 5}The challenge proves trivial for someone of {actor.possessive_adj} skill level.{ELIF difficulty > 15}Even with the considerable difficulty, {actor.possessive_adj} training proves sufficient.{ELSE}The task is managed competently.{ENDIF} {IF witnesses}Those watching {RANDOM[nod in appreciation|show visible impression|silently acknowledge the demonstration of skill]}.{ENDIF}",
            
            "{actor.name}'s mastery of {domain} shines as {actor.subjective} {action}. {IF actor.emotions.pride > 5}{Actor.subjective} {RANDOM[takes evident satisfaction in|displays confidence throughout|performs with flourish during]} the accomplishment.{ELSE}{Actor.subjective} {RANDOM[proceeds methodically|works without unnecessary display|focuses entirely on the task]}.{ENDIF} {IF mentor_present}The approving nod from {mentor.name} confirms the quality of the performance.{ENDIF}",
            
            "Years of {domain} training pay off as {actor.name} confidently {action}. {IF high_pressure}Despite the pressure, {actor.possessive_adj} hands remain steady and {actor.possessive_adj} judgment sound.{ENDIF} {IF world_state.active_global_threats && domain == 'SURVIVAL'}Skills like these become vital with {threat_name} threatening the region.{ELIF world_state.economic_status == 'DEPRESSION' && domain == 'CRAFTING'}Such talent is ever more valuable when resources are scarce and must be utilized effectively.{ENDIF}"
        ],
        
        "domain_check_failure": [
            "Despite {domain} knowledge, {actor.name} fails to {action}. {IF margin < -5}The attempt falls dramatically short of success, {RANDOM[with immediately obvious errors|leading to a clearly unsuccessful outcome|mishandling the fundamentals of the task]}.{ELSE}The attempt nearly succeeds, but {RANDOM[a minor error proves critical|falls just short of the required standard|lacks some essential element]}.{ENDIF} {IF actor.emotions.pride > 5}{Actor.subjective} {RANDOM[winces at the blow to {actor.possessive_adj} ego|quickly tries to recover composure|shows momentary frustration]}.{ENDIF}",
            
            "{actor.name}'s {domain} skills prove inadequate as {actor.subjective} attempt{IF actor.gender == 'neutral'}|s{ENDIF} to {action}. {IF difficult > 15}The difficulty was significant, and even experts might struggle.{ELSE}The task should have been manageable, but circumstances or errors intervened.{ENDIF} {IF mentor_present}{Mentor.name} {RANDOM[offers a subtle correction|makes a mental note of the area needing improvement|provides an encouraging word despite the setback]}.{ENDIF}",
            
            "The challenge exceeds {actor.name}'s {domain} abilities when {actor.subjective} tr{IF actor.gender == 'neutral'}y{ELSE}ies{ENDIF} to {action}. {IF actor.emotions.anger > 5}{Actor.subjective} {RANDOM[curses under {actor.possessive_adj} breath|shows visible frustration|briefly loses composure]}.{ELIF actor.emotions.pride > 5}{Actor.subjective} quickly {RANDOM[makes excuses|blames external factors|attempts to downplay the failure]}.{ELSE}{Actor.subjective} {RANDOM[accepts the outcome calmly|learns from the mistake|takes the setback in stride]}.{ENDIF}"
        ],
        
        # NPC interactions
        "npc_interaction": [
            "{actor.name} approaches {npc.name}, {IF relationship.value > 5}with the easy manner of established rapport{ELIF relationship.value < -5}barely concealing tension from previous encounters{ELSE}maintaining a neutral, careful demeanor{ENDIF}. {npc.name} {IF npc.emotions.joy > 5}brightens visibly{ELIF npc.emotions.fear > 5}tenses momentarily{ELIF npc.emotions.anger > 5}hardens their expression{ELSE}acknowledges the approach with a measured nod{ENDIF}. {IF world_state.political_stability == 'UNREST'}They both instinctively keep their voices lower than normal, aware of potential listeners.{ENDIF}",
            
            "The conversation between {actor.name} and {npc.name} {IF relationship.trust > 5}flows with the ease of mutual trust{ELIF relationship.value < 0}remains guarded, with careful consideration of each word{ELSE}proceeds with standard social courtesies{ENDIF}. {IF world_state.economic_status == 'DEPRESSION'}Talk inevitably turns to the hardships affecting everyone.{ELIF world_state.active_global_threats}The shadow of {threat_name} looms over their discussion, unavoidable context for all interaction now.{ELIF topic == 'business'}They discuss terms with {RANDOM[straightforward pragmatism|attention to mutual benefit|careful negotiation of details]}.{ENDIF}",
            
            "{npc.name} reacts to {actor.name}'s presence with {IF first_meeting}the careful assessment given to strangers{ELIF relationship.familiarity > 7}warm recognition{ELIF relationship.respect > 5}courteous acknowledgment{ELIF relationship.value < -3}poorly concealed distaste{ELSE}neutral acknowledgment{ENDIF}. {IF npc.role == 'merchant' && world_state.economic_status == 'RECESSION'}Their merchant's smile seems strained, the worries of dwindling business evident despite professional demeanor.{ELIF npc.role == 'guard' && world_state.political_stability == 'UNREST'}They maintain the rigid posture of authority, but their eyes constantly scan for potential trouble.{ELIF npc.role == 'scholar' && topic == 'lore'}Their eyes light up at the chance to discuss their specialty, momentarily forgetting other concerns.{ENDIF}"
        ],
        
        # World state events
        "GLOBAL_ECONOMIC_SHIFT": [
            "The markets in {location} {IF economic_status=='RECESSION' || economic_status=='DEPRESSION'}stand half-empty, with {RANDOM[vendors calling desperately for business|basic goods commanding inflated prices|people arguing over dwindling resources]}{ELSE}overflow with activity, {RANDOM[exotic goods appearing in abundance|vendors competing for attention|coin flowing freely between buyers and sellers]}{ENDIF}. Conversations everywhere turn to the {economic_status} economy and its effects on daily life. {IF political_stability=='UNREST'}Guards patrol more frequently, alert for the desperation that often breeds crime and rebellion.{ENDIF}",
            
            "A sense of {IF economic_status=='RECESSION'}worry{ELIF economic_status=='DEPRESSION'}desperation{ELIF economic_status=='BOOM'}optimism{ELSE}cautious stability{ENDIF} permeates the region. {IF economic_status=='DEPRESSION'}Children with hollow cheeks watch merchants pack unsold wares, while craftspeople sit idle beside workshops gone quiet.{ELIF economic_status=='BOOM'}New construction rises in every district, apprentices are in high demand, and even the poorest quarters see improvements to their circumstances.{ENDIF} {IF active_global_threats}The economic situation {RANDOM[complicates responses to|diverts attention from|changes priorities regarding]} the threat of {threat_name}.{ENDIF}",
            
            "{IF economic_status=='RECESSION' || economic_status=='DEPRESSION'}Tax collectors move door to door accompanied by guards, met with either empty coin purses or hostile stares. The lord's recent proclamation about 'necessary sacrifices' has done little to ease the burden.{ELSE}The treasury has announced new public works, and craftsmen compete fiercely for contracts. Recent prosperity has allowed for infrastructure long neglected to finally receive attention.{ENDIF} Travelers bring news that {RANDOM[neighboring regions face similar conditions|the situation is worse in lands to the east|the capital has been affected even more severely]}."
        ],
        
        "GLOBAL_POLITICAL_SHIFT": [
            "Tension is palpable in {location} as news spreads of {political_event}. {IF political_stability=='UNREST'}Armed patrols have doubled, checking papers and questioning strangers with heightened suspicion.{ELIF political_stability=='REBELLION'}Barricades appear at night and disappear by morning, while symbols of resistance are etched on walls and quickly covered over.{ELIF political_stability=='WAR'}Recruitment officers work the crowds while blacksmiths focus exclusively on weapons and armor, turning away other commissions.{ENDIF} {IF economic_status=='DEPRESSION'}The already-suffering populace {RANDOM[greets the news with resignation|fears what further hardship may come|whispers of additional causes for discontent]}.{ENDIF}",
            
            "The recent political shifts towards {political_stability} have transformed daily life. {IF political_stability=='PEACEFUL'}Where soldiers once stood, merchants now set up stalls. Children play in streets that used to empty at dusk.{ELIF political_stability=='WAR'}Homes display black mourning cloth for sons and daughters sent to battle. Strategic resources are strictly rationed.{ENDIF} {IF location_type=='border_region'}This frontier zone feels the changes most acutely, with {RANDOM[border controls intensified|refugee movements evident|military presence significantly altered]}.{ENDIF} Conversations everywhere turn to questions of loyalty, survival, and what comes next.",
            
            "Proclamations nailed to posts announce the new policies following {political_event}. {IF political_stability=='UNREST' || political_stability=='REBELLION'}People read them in furtive glances, careful not to show too much interest or dismay.{ELSE}Citizens openly discuss the implications, with opinions freely shared.{ENDIF} {IF actor.domain.LORE > 4 || actor.domain.POLITICS > 3}To your educated eye, the true motivations behind these pronouncements seem to be {RANDOM[consolidation of power|response to external pressures|appeasement of powerful factions|preparation for future confrontation]}.{ENDIF} The effects will undoubtedly reach far beyond the immediate concerns addressed."
        ],
        
        "AMBIENT_WORLD_NARRATIVE": [
            "{current_season}'s character is fully expressed today. {IF current_season=='winter'}Cold seeps through layers of clothing, breath forms clouds, and people hurry rather than linger.{ELIF current_season=='spring'}New growth pushes through soil, birds construct nests, and a gentle warmth replaces winter's bite.{ELIF current_season=='summer'}Heat ripples the air above stone pathways, shade is sought and valued, and the scent of ripening fruit carries on the breeze.{ELIF current_season=='autumn'}Trees display their fiery transformation, harvests are gathered with haste, and morning frost warns of colder days ahead.{ENDIF} {IF economic_status=='DEPRESSION'}Even nature's beauty is overshadowed by more pressing concerns of survival.{ELIF active_global_threats}Yet even as the seasons continue their ancient cycle, the threat of {threat_name} weighs on every mind.{ENDIF}",
            
            "Daily life in {location} follows its rhythm, though {IF political_stability=='UNREST'}undercurrents of tension disrupt the usual patterns{ELIF political_stability=='WAR'}each routine now serves the war effort in some capacity{ELIF economic_status=='BOOM'}prosperity has accelerated the pace and raised spirits{ELIF economic_status=='DEPRESSION'}hardship has slowed activities and dampened interactions{ELSE}nothing extraordinary disrupts the established customs{ENDIF}. Children {IF political_stability=='PEACEFUL' || political_stability=='STABLE'}play in open spaces, their games mimicking adult occupations{ELSE}stay closer to home, their games now mimicking the conflicts they overhear{ENDIF}. The cycle of work, meals, and rest continues despite greater circumstances, as it always has and always will.",
            
            "Conversations overheard while passing through {location} reveal the primary concerns of its people. {IF economic_status=='RECESSION'}The rising cost of essentials dominates discussion, with tips shared on substitutions and economies.{ELIF political_stability=='REBELLION'}Coded language and significant glances accompany talk of recent events, true meanings hidden beneath innocuous words.{ELIF active_global_threats}The threat of {threat_name} infects every topic, from practical preparations to theological interpretations of why it's happening.{ELSE}Ordinary matters prevail - weather predictions, family news, local gossip about neighbors and notables.{ENDIF} Through these mundane exchanges, the true state of the world reveals itself to attentive ears."
        ],
        
        # Character emotional responses
        "emotional_response": [
            # Joy-based responses
            "{IF actor.emotions.joy > 7}A bright smile transforms {actor.name}'s face, reaching all the way to {actor.possessive_adj} eyes. {Actor.possessive_adj} posture becomes more open, more energetic.{ELIF actor.emotions.joy > 5}A smile plays at the corners of {actor.name}'s mouth, and there's a lightness in {actor.possessive_adj} step.{ELIF actor.emotions.joy > 3}A subtle but unmistakable contentment shows in {actor.name}'s expression.{ENDIF}",
            
            # Fear-based responses
            "{IF actor.emotions.fear > 7}{Actor.name}'s eyes dart rapidly, scanning for threats. {Actor.possessive_adj} voice drops to a whisper, and {actor.possessive_adj} hands tremble slightly.{ELIF actor.emotions.fear > 5}{Actor.name} becomes more guarded, keeping solid objects at {actor.possessive_adj} back and maintaining awareness of exits.{ELIF actor.emotions.fear > 3}A subtle tension enters {actor.name}'s posture, and {actor.possessive_adj} responses become more measured, cautious.{ENDIF}",
            
            # Anger-based responses
            "{IF actor.emotions.anger > 7}A flush crawls up {actor.name}'s neck, and {actor.possessive_adj} words come through clenched teeth. {Actor.possessive_adj} hands ball into fists reflexively.{ELIF actor.emotions.anger > 5}{Actor.name}'s voice takes on an edge, and {actor.possessive_adj} movements become sharp, abrupt.{ELIF actor.emotions.anger > 3}A momentary hardness crosses {actor.name}'s features before {actor.subjective} masters it.{ENDIF}",
            
            # Sorrow-based responses
            "{IF actor.emotions.sorrow > 7}{Actor.name}'s shoulders slump noticeably, and {actor.possessive_adj} eyes remain downcast. A slight tremor in {actor.possessive_adj} voice betrays deeper emotions.{ELIF actor.emotions.sorrow > 5}A shadow passes over {actor.